# Screensaver — ghostty fullscreen, no decorations
windowrule = float on, match:class org.screensaver
windowrule = fullscreen on, match:class org.screensaver


# Zathura — glass float
windowrule = float on, match:class ^(org.pwmt.zathura)$
windowrule = center on, match:class ^(org.pwmt.zathura)$
windowrule = size 1100 750, match:class ^(org.pwmt.zathura)$
windowrule = opacity 0.88 0.82, match:class ^(org.pwmt.zathura)$

# mpv — centered floating popup
windowrule = float on, match:class ^(mpv)$
windowrule = center on, match:class ^(mpv)$
windowrule = size 960 540, match:class ^(mpv)$

# filemanager picker — centered floating popup, same treatment as mpv
windowrule = float on, match:class ^(com.codetesla51.filemanager.picker)$
windowrule = center on, match:class ^(com.codetesla51.filemanager.picker)$
windowrule = size 960 540, match:class ^(com.codetesla51.filemanager.picker)$
