foreground            #ede1d4
background            #18130b
selection_foreground  #f9debb
selection_background  #55442a
url_color             #f2be6e
cursor                #f2be6e
cursor_text_color     #442c00

active_tab_foreground   #442c00
active_tab_background   #f2be6e
inactive_tab_foreground #d2c4b4
inactive_tab_background #4f4539

# Black
color0 #18130b
color8 #4f4539

# Red
color1 #ffb4ab
color9 #ffb4ab

# Green
color2 #b6cea3
color10 #b6cea3

# Yellow
color3 #dcc3a1
color11 #dcc3a1

# Blue
color4 #f2be6e
color12 #f2be6e

# Magenta
color5 #614000
color13 #614000

# Cyan
color6 #394c2b
color14 #394c2b

# White
color7 #ede1d4
color15 #d2c4b4
