-- ─────────────────────────────────────────────
--   Hyprland Colors — Lua (generated by Matugen)
--   Mirrors colors.conf · do not edit manually
--   Source template: matugen/templates/hyprland.lua
-- ─────────────────────────────────────────────
active_border = "f2be6e"
inactive_border = "4f4539"
background = "18130b"

return {
    active_border = active_border,
    inactive_border = inactive_border,
    background = background,
}
